### ISSUE TITLE
Patching VolspotConnect2 config changes Spotify Connect device name to Vollibrespot

### ISSUE THREAD

**Issue by anLizard** [Saiyato/volumio-snapserver-plugin#1]
Steps to reproduce:

1. Install Snapserver plugin
2. Enable Snapserver Plugin
3. Enable VolspotConnect2 integration and patch config files
4. Restart Volumio Spotify Connect 2 Plugin
--> Device now shows up as "Vollibrespot" instead of the device's hostname in the Spotify Client

More details:
Raspberry Pi 3
Volumio 2.917
SnapServer Plugin 1.3.2
Spotify Connect 2 Plugin 1.0.5

Please have a look into this! I could not figure out a way to change it back to the hostname and retain Snapserver functionality.

**Comment by Saiyato** [comment]
Thanks for the specific report, I will check on my Pi2 to reproduce (and otherwise see if I can use my Pi3 for testing :wink:).
Allow me to check this out!

**Comment by Saiyato** [comment]
Seems like the install script isn't working as expected, the RC (now testing in 3.129) behaves differently than the (very old) test version of Volumio on Buster I've been working with prior to the new releases.

**Comment by Saiyato** [comment]
I think I found the problem, not Volumio2 or 3 related, just a mismatch in property-mapping of the Spotify plugin.
Can you re-test with version 1.3.4?

**Comment by anLizard** [comment]
Just tested it on 1.3.5, issue is still happening, sadly.
Here's the order in which I did things to test it again:

1. Disabled and unsintalled Spotify Connect, then Snapserver plugin, rebooted.
2. Installed and enabled Spotify Connect Plugin.
3. Checked for name. It used the correct name (hostname)

4. Installed and enabled Snapserver plugin. 
5. Enabled Spotify Connect Integration and patched config.
6. Restarted Spotify Connect Plugin.
7. Checked for name. It used the incorrect name (Vollibrespot)

**Comment by anLizard** [comment]
Just tested the new version 1.3.5, and its fixed now! Thanks so much!
Yeah, I did make a little mistake up there, meant to write 1.3.4 in the previous comment.

**Comment by Saiyato** [comment]
No worries, thanks for the feedback! :)

**Comment by anLizard** [comment]
Kind of off-topic, but I guess I have one more question.
How did you change the Spotify Connect Device name in the first place?
I'd like to rename it on one of my Raspberry Pi's manually,  but changing `--name '${devicename}'` in `/data/plugins/music_service/volspotconnect2/volspotconnect2.tmpl` to my desired value does not seem to make any difference.

**Comment by Saiyato** [comment]
Since a few months that plugin uses another template, it uses TOML-configs now. You should edit `/data/plugins/music_service/volspotconnect2/volspotify.tmpl` and then restart the plugin :wink:
