### ISSUE TITLE
MDP Output can't be patched

### ISSUE THREAD

**Issue by anLizard** [Saiyato/volumio-snapserver-plugin#4]
Volumio 3.198
Snapserver 1.3.9
Raspberry Pi 3

When I try to patch MDP Output and reboot, MDP stays unpatched in the UI, and MDP audio doesn't get sent by Snapcast.
Spotify seems to work though.

Steps to reproduce:
1. Install Snapserver plugin
2. Patch MDP and VolspotConnect2
3. Reboot
4. Play MDP Audio, e.g. Web Radio

Result:
* MDP is not displayed as patched in UI, VolspotConnect2 does display as patched.
* MDP Audio does not play on connected Snapcast Clients (e.g. Web Radio).
* Spotify Connect Output plays on connected clients.

![image](https://user-images.githubusercontent.com/48686356/156564249-19df71d9-9127-45c8-b915-49565ab98b58.png)

Live Log when patching:
```
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 0
info: CoreCommandRouter::volumioGetQueue
info: CoreStateMachine::getQueue
info: CorePlayQueue::getQueue
info: CoreCommandRouter::executeOnPlugin: system , getHwuuid
info: CALLMETHOD: system_controller system enableLiveLog true
info: CoreCommandRouter::executeOnPlugin: system , enableLiveLog
info: Launching a new LiveLog session
info: CoreCommandRouter::volumioGetState
info: CorePlayQueue::getTrack 0
info: Listing playlists
info: Listing playlists
info: CALLMETHOD: audio_interface snapserver updatePlayerConfigs [object Object]
info: CoreCommandRouter::executeOnPlugin: snapserver , updatePlayerConfigs
/bin/sed: can't read /data/plugins/music_service/spop/spop.conf.tmpl: No such file or directory
/bin/sed: can't read /data/plugins/music_service/spop/spop.conf.tmpl: No such file or directory
info: Successfully executed script {/data/plugins/audio_interface/snapserver/mpd_switch_to_fifo.sh}
 volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart mpd.service
pam_unix(sudo:session): session opened for user root by (uid=0)
Stopping Music Player Daemon...
mpd.service: Succeeded.
Stopped Music Player Daemon.
Starting Music Player Daemon...
Mar 03 12:26 : exception: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
Mar 03 12:26 : exception: Input plugin 'tidal' is unavailable: No Tidal application token configured
Mar 03 12:26 : exception: Input plugin 'qobuz' is unavailable: No Qobuz app_id configured
Started Music Player Daemon.
pam_unix(sudo:session): session closed for user root
info: CoreCommandRouter::executeOnPlugin: mpd , mpdEstablish
error: updateQueue error: null
```

**Comment by Saiyato** [comment]
This way of working has been deprecated, I'm testing AAMPP implementation in the development branch. This should be released soon and will require no configuration. It just works out of the box for all services :smile:

**Comment by anLizard** [comment]
Very nice! Can't wait to try it out!

**Comment by Saiyato** [comment]
Hmmm, first failed test -> AirPlay 👎 
MPD, YT Cast & Volspotconnect seem to work though. I need to strip some old code, because I don't need to "patch" all configs anymore (yay!), I'll try to test some more next week.

**Comment by Hendrick42** [comment]
Is there an update on this?
I can "patch" MPD and streaming is working. But this does not survive a reboot...

Volumi 3.301
Snapserver 1.3.9

**Comment by Saiyato** [comment]
Please note that it's not done yet, but the new zip-file is a working version, which respects the AAMPP architecture. So no more difficult configs, it works for everything... but AirPlay (for some reason, I cannot get this to work). Use version 2.1.4 and up

**Comment by Saiyato** [comment]
In other words, you'll need to reinstall _manually_ unfortunately :wink: I will not release to the store yet, because I want to finish the snapweb config and possibly some other options I now brutally removed :)

**Comment by anLizard** [comment]
So if I want to test it, I should install the version on the development branch?
I looked inside install.sh and saw the `echo "## Installing SnapServer plugin v1.3.9 ##"`

**Comment by Saiyato** [comment]
Oh, good find, yes I did not update install.sh yet. The package.json should reflect the proper version (which is also shown in the Volumio GUI)

**Comment by anLizard** [comment]
Tried to install, but it failed

```
volumio@pimulti:~$ cd volumio-snapserver-plugin-development/
volumio@pimulti:~/volumio-snapserver-plugin-development$ volumio plugin install

This command will install the plugin on your device

 ================================ WARNING ====================================

This plugin is not verified by Volumio. Installing it is UNSAFE and can make your system UNSTABLE!
You are STRONGLY advised not to install plugins manually, better wait they are officially available.

 =============================================================================
? Do you want to install this plugin anyway? Yes
Compressing the plugin
No modules found, running "npm install"
npm notice created a lockfile as package-lock.json. You should commit this file.
Plugin succesfully compressed
/bin/mv: target '/tmp/plugins/snapserver.zip' is not a directory
(node:3146) UnhandledPromiseRejectionWarning: Error: Command failed: /bin/mv *.zip /tmp/plugins/snapserver.zip
/bin/mv: target '/tmp/plugins/snapserver.zip' is not a directory

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at /volumio/pluginhelper.js:778:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3146) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3146) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by anLizard** [comment]
Ok, I installed from the main branch and it works!
Radio, Spotify, Youtube, it all pipes through. :)
and I had to change no settings at all!
